[workspace]
authors = ["Ben Moss <ben@mossity.com>"]
channels = ["https://prefix.dev/conda-forge"]
name = "pixi-update"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
version = "0.2.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
rust = ">=1.90.0,<1.91"

[feature.lint.dependencies]
basedpyright = ">=1.31.4,<2"
dprint = ">=0.49.1,<0.51"
lefthook = ">=1.13.6,<2"
ruff = ">=0.12,<0.13"
taplo = ">=0.10.0,<0.11"
typos = ">=1.29.10,<2"

[environments]
lint = { features = ["lint"] }

[feature.lint.tasks]
cargo-clippy = "cargo clippy --all-targets --workspace -- -D warnings"
cargo-fmt = "cargo fmt --all"
dprint-check = { cmd = "dprint check --log-level=silent", description = "Check formatting with dprint" }
dprint-fmt = { cmd = "dprint fmt --incremental=false", description = "Format with dprint" }
lefthook = { cmd = "lefthook", description = "Run lefthook" }
lint = { depends-on = [
  "lint-fast",
  "lint-slow",
], description = "Run all linters and formatters on all code" }
lint-fast = { cmd = "lefthook run pre-commit --all-files --force", description = "Run all fast linters and formatters on all code (no clippy)" }
lint-slow = { cmd = "lefthook run pre-push --all-files --force", description = "Run all slow linters and formatters on all code" }
pre-commit-install = "lefthook install"
pre-commit-install-minimal = "lefthook install pre-commit"
ruff-format = "ruff format --exit-non-zero-on-format --force-exclude"
ruff-lint = "ruff check --fix --exit-non-zero-on-fix --force-exclude"
toml-format = { cmd = "taplo fmt", env = { RUST_LOG = "warn" } }
toml-lint = "taplo lint --verbose **/pixi.toml"
typecheck-python = "basedpyright"
typos = "typos --force-exclude"

[package]
name = "pixi-outdated"

[package.build.backend]
name = "pixi-build-rust"
version = "0.4.*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
