[workspace]
authors = ["Ben Moss <ben@mossity.com>"]
channels = ["conda-forge"]
name = "examples"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.0,<3.13"

[pypi-dependencies]
cowsay = ">=5.0, <6"
